// Night/floor configuration — the five nights of the House of Good Children.
// Each night is one floor of the house, with its own enemies, boss, memory,
// keepsake, and the rule that appears on the Dormitory wall afterwards.

export const NIGHTS = {
  1: {
    floor: 'NURSERY ROT',
    boss: 'THE NANNY WITH NO FACE',
    bossKind: 'nanny',
    enemyKinds: ['mouse', 'crawler', 'doll'],
    keepsake: 'ribbon',
    keepsakeName: 'the burned ribbon',
    keepsakeDesc: '+1 stitch, every night after.',
    rule: 'RULE 6: GOOD CHILDREN DO NOT REMEMBER',
    bossIntro: 'Hush now. Little dolls should be SLEEPING.',
    dropText: 'Something falls from the pram. A ribbon, half-burned. It smells like smoke and old lullabies.',
    memory: [
      'The candles remember for you.',
      'A small room. A smaller chair. A child sits facing the corner, shoulders shaking without a sound.',
      'MOTHER MERCY: "Good children do not cry. Crying is asking. And what do we say about asking?"',
      'The child\'s voice, very quiet: "Good children do not ask why."',
      'MOTHER MERCY: "There. All better. Sit until you are dry."',
      'The child holds something under their shirt. Something soft. Something with one button eye.',
      'The memory goes dark, like a snuffed candle.',
    ],
    palette: { planks: ['#43301f', '#4a3524', '#3c2b1c', '#463222'], wall: '#151020' },
  },
  2: {
    floor: 'THE LESSON HALL',
    boss: 'THE TEACHER OF QUIET',
    bossKind: 'teacher',
    enemyKinds: ['wraith', 'mimic', 'mouse', 'doll'],
    keepsake: 'chalk',
    keepsakeName: 'the chalk stub',
    keepsakeDesc: 'The candleflame drinks deeper. (+50% flame gained.)',
    rule: 'RULE 7: GOOD CHILDREN DO NOT SPEAK FIRST',
    bossIntro: 'Raise your hand if you wish to SCREAM.',
    dropText: 'A stub of chalk rolls from the Teacher\'s sleeve. Someone has bitten it. Someone small.',
    memory: [
      'The candles remember for you.',
      'Rows of desks. Rows of children. Nobody moves. Nobody has moved for a very long time.',
      'On the blackboard, in perfect letters: I WILL NOT ASK ABOUT THE FOURTH FLOOR. Written four hundred times.',
      'A child\'s hand is raised in the back row. It has been raised so long the arm has gone thin as a candlewick.',
      'THE TEACHER, without turning: "I see no questions here."',
      'The chalk keeps writing by itself.',
      'The memory goes dark, like a snuffed candle.',
    ],
    palette: { planks: ['#2e3230', '#343a36', '#2a2e2c', '#313632'], wall: '#101816' },
  },
  3: {
    floor: 'THE LONG KITCHEN',
    boss: 'THE COOK WHO STIRS',
    bossKind: 'cook',
    enemyKinds: ['spoon', 'porridge', 'crawler', 'doll'],
    keepsake: 'spoon',
    keepsakeName: 'the silver spoon',
    keepsakeDesc: 'Stitches found on the floor mend twice as well.',
    rule: 'RULE 8: GOOD CHILDREN CLEAN THEIR PLATES',
    bossIntro: 'Sit. Eat. It is RUDE to leave before you are finished.',
    dropText: 'A silver spoon clatters from the Cook\'s apron. A name is scratched into the handle. The scratches are tooth-marks.',
    memory: [
      'The candles remember for you.',
      'A table longer than the room that holds it. Bowls of grey porridge, all full, all cold.',
      'A child sits before one bowl. The chair is bolted to the floor.',
      'MOTHER MERCY: "You will sit there until you are grateful."',
      'The child whispers to the porridge, like a prayer: "I\'m grateful. I\'m grateful. I\'m grateful."',
      'The bowl never empties. That is the trick of it. The bowl was never meant to empty.',
      'The memory goes dark, like a snuffed candle.',
    ],
    palette: { planks: ['#3a2e22', '#443628', '#33291e', '#3e3225'], wall: '#1a1410' },
  },
  4: {
    floor: 'THE LAUNDRY BELOW',
    boss: 'THE LAUNDRESS',
    bossKind: 'laundress',
    enemyKinds: ['sheet', 'hound', 'mouse', 'doll'],
    keepsake: 'musicbox',
    keepsakeName: 'the music box',
    keepsakeDesc: 'It plays when you move quickly. Dodge recovers twice as fast.',
    rule: 'RULE 9: GOOD CHILDREN COME OUT CLEAN',
    bossIntro: 'Such a DIRTY little doll. Into the water with you.',
    dropText: 'A music box drops from the Laundress\'s wet apron. It plays three notes of a lullaby, then thinks better of it.',
    memory: [
      'The candles remember for you.',
      'Steam. Tubs of grey water in a row. Small clothes hung on lines, none of them dry, none of them claimed.',
      'A child stands in a tub, scrubbed pink and raw. "Am I clean yet?"',
      'THE LAUNDRESS: "Almost, pet. There is a spot that will not come out."',
      'The child, shivering: "Where?"',
      'The Laundress touches the child\'s chest, just over the heart. "Here. There is always one here."',
      'The memory goes dark, like a snuffed candle.',
    ],
    palette: { planks: ['#26303a', '#2c3844', '#222c34', '#293440'], wall: '#0e141c' },
  },
  5: {
    floor: 'THE ATTIC OF RULES',
    boss: 'MOTHER MERCY',
    bossKind: 'mercy',
    enemyKinds: ['wraith', 'sheet', 'mouse', 'doll'],
    keepsake: 'locket',
    keepsakeName: 'the mother\'s locket',
    keepsakeDesc: 'It will not open. It does not need to.',
    rule: 'RULE 1: GOOD CHILDREN LOVE MOTHER MERCY',
    bossIntro: 'There you are. My good, good child. Come and be FORGIVEN.',
    dropText: 'A locket falls where Mother Mercy stood. It is warm, and it beats, very faintly, like a small tired heart.',
    memory: [
      'The candles remember for you.',
      'The attic. Boxes of small shoes. A ledger of names, every name crossed out and rewritten as GOOD CHILD.',
      'A girl kneels at the window, holding a stitched rabbit with one button eye. "If I drop you, you\'ll land soft. And you can go get help."',
      'MOTHER MERCY, from the stairs: "Elsie. What do we say about the windows?"',
      'The girl doesn\'t answer. She hugs the rabbit hard enough to feel the candle inside it, still warm.',
      'She whispers into its missing ear: "Come back. Promise you\'ll come back."',
      'You remember falling. You remember landing soft. You remember the house was already burning behind the glass.',
      'The memory goes dark. This time it is your own.',
    ],
    palette: { planks: ['#33222a', '#3c2932', '#2d1e25', '#38262e'], wall: '#160d12' },
  },
};

export const LAST_NIGHT = 5;

// Keepsake pickup sprites are looked up by these ids in sprites.js (SPR[id]).
export const KEEPSAKE_ORDER = ['ribbon', 'chalk', 'spoon', 'musicbox', 'locket'];

// The Pretend pool. Two are offered per run.
export const PRETENDS = [
  { id: 'brave', name: 'PRETEND YOU ARE BRAVE', desc: 'Double damage while below half stitches.' },
  { id: 'loved', name: 'PRETEND YOU ARE LOVED', desc: 'Two extra stitches, sewn with borrowed thread.' },
  { id: 'quick', name: 'PRETEND YOU ARE QUICK', desc: 'Faster feet, and your dodge recovers sooner.' },
  { id: 'ember', name: 'PRETEND YOU ARE WARM', desc: 'The candleflame gathers half again as fast.' },
  { id: 'mended', name: 'PRETEND YOU ARE WHOLE', desc: 'A stitch mends itself each time a room goes quiet.' },
  { id: 'fierce', name: 'PRETEND YOU ARE FIERCE', desc: 'The needle swings faster than fear.' },
];
